const gradientPrimary = "linear-gradient(135deg, #8b5cf6 0%, #6d28d9 100%)";

export const authStyles = {
  page: {
    minHeight: "100vh",
    background: "radial-gradient(ellipse at top, rgba(139,92,246,0.15) 0%, var(--paper) 55%)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "48px 20px",
    fontFamily: "var(--font-body)",
    color: "var(--ink)",
  },
  brand: { display: "flex", alignItems: "center", gap: 10, marginBottom: 32 },
  brandMark: {
    width: 36,
    height: 36,
    borderRadius: 10,
    background: gradientPrimary,
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "var(--font-display)",
    fontWeight: 700,
    fontSize: 18,
    boxShadow: "0 4px 16px rgba(139,92,246,0.45)",
  },
  brandName: { fontFamily: "var(--font-display)", fontWeight: 700, fontSize: 20 },
  card: {
    width: "100%",
    maxWidth: 400,
    background: "var(--paper-raised)",
    border: "1px solid var(--ink-15)",
    borderRadius: 20,
    padding: 36,
    boxShadow: "0 25px 60px rgba(0,0,0,0.4)",
  },
  h1: { fontSize: 26, marginBottom: 8 },
  sub: { fontSize: 14, color: "var(--ink-45)", marginBottom: 26 },
  form: { display: "flex", flexDirection: "column", gap: 18 },
  label: { display: "flex", flexDirection: "column", gap: 8, fontSize: 13, color: "var(--ink-70)" },
  input: {
    padding: "13px 16px",
    borderRadius: 12,
    border: "1px solid var(--ink-15)",
    fontSize: 15,
    background: "var(--paper)",
    color: "var(--ink)",
    outline: "none",
    transition: "border-color 200ms, box-shadow 200ms",
  },
  submitBtn: {
    marginTop: 6,
    padding: "15px 20px",
    borderRadius: 12,
    border: "none",
    background: gradientPrimary,
    color: "#fff",
    fontSize: 15,
    fontWeight: 600,
    boxShadow: "0 10px 28px rgba(139,92,246,0.4)",
    cursor: "pointer",
  },
  error: {
    fontSize: 13,
    color: "#fca5a5",
    background: "rgba(239,68,68,0.12)",
    border: "1px solid rgba(239,68,68,0.25)",
    padding: "10px 14px",
    borderRadius: 10,
  },
  footNote: { fontSize: 13, color: "var(--ink-45)", marginTop: 22, textAlign: "center" },
  link: { color: "var(--gold-ink)", fontWeight: 600 },
};
