export const authStyles = {
  page: {
    minHeight: "100vh",
    background: "var(--paper)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "48px 20px",
    fontFamily: "var(--font-body)",
    color: "var(--ink)",
  },
  brand: { display: "flex", alignItems: "center", gap: 10, marginBottom: 32 },
  brandMark: {
    width: 34,
    height: 34,
    borderRadius: 8,
    background: "var(--ink)",
    color: "var(--gold)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "var(--font-display)",
    fontWeight: 700,
    fontSize: 18,
  },
  brandName: { fontFamily: "var(--font-display)", fontWeight: 700, fontSize: 20 },
  card: {
    width: "100%",
    maxWidth: 400,
    background: "var(--paper-raised)",
    border: "1px solid var(--ink-15)",
    borderRadius: 14,
    padding: 32,
  },
  h1: { fontSize: 24, marginBottom: 8 },
  sub: { fontSize: 14, color: "var(--ink-45)", marginBottom: 24 },
  form: { display: "flex", flexDirection: "column", gap: 16 },
  label: { display: "flex", flexDirection: "column", gap: 8, fontSize: 13, color: "var(--ink-70)" },
  input: {
    padding: "12px 14px",
    borderRadius: 8,
    border: "1px solid var(--ink-15)",
    fontSize: 15,
    background: "var(--paper)",
    color: "var(--ink)",
  },
  submitBtn: {
    marginTop: 4,
    padding: "13px 20px",
    borderRadius: 8,
    border: "none",
    background: "var(--ink)",
    color: "var(--paper-raised)",
    fontSize: 15,
    fontWeight: 600,
  },
  error: {
    fontSize: 13,
    color: "var(--brick)",
    background: "rgba(181,72,45,0.08)",
    padding: "10px 12px",
    borderRadius: 8,
  },
  footNote: { fontSize: 13, color: "var(--ink-45)", marginTop: 20, textAlign: "center" },
  link: { color: "var(--forest)", fontWeight: 600 },
};
